# Generated by Django 5.0.6 on 2024-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Titanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_id", models.IntegerField(unique=True)),
                ("survived", models.BooleanField()),
                ("pclass", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.FloatField(null=True)),
                ("sibsp", models.IntegerField()),
                ("parch", models.IntegerField()),
                ("ticket", models.CharField(max_length=50)),
                ("fare", models.FloatField()),
                ("cabin", models.CharField(max_length=50, null=True)),
                ("embarked", models.CharField(max_length=100)),
            ],
        ),
    ]
