# Generated by Django 5.0.6 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("titanic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titanic",
            name="passenger_id",
            field=models.IntegerField(),
        ),
    ]
